use_frameworks!

platform :ios, '9.0'

target 'MonetaryCounterView_Example' do
  pod 'MonetaryCounterView', :path => '../'

  target 'MonetaryCounterView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
